# Generated by Django 4.1.7 on 2023-03-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment_created_at_comment_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_square',
            field=models.ImageField(blank=True, null=True, upload_to='post_images_square/'),
        ),
    ]
