# Generated by Django 4.1.7 on 2023-03-26 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+77011112233'", regex='^\\+7\\d{10}$')], verbose_name='Номер телефона'),
        ),
    ]
